config:
  aws:region: us-west-2
  aws-native:region: us-west-2
  openpipe:ANTHROPIC_API_KEY:
    secure: AAABAIib0LJsmJHL2E/qDWve1ex9U0ky6eZNS8MwZEcx0VdpjY588ZRzyDx84t20iC/6XzwENvN9tkbaIEx2uznP1AXuoWoD7HTw+B09hc8i0ScTCfE8WDXfbgPF7xIU3f+OIxNs1ltBhXJ7AjoMWQxrXw==
  openpipe:APP_SUBDOMAIN: stage
  openpipe:AUTHENTICATED_SYSTEM_KEY:
    secure: AAABAIF/+V67LPOdOL1TJ6vYspfsshXqklCatXW4iwT9xkQiS5iQpIexXPiFAp2tFWwSi8w63gPExslbwltxbg==
  openpipe:AZURE_STORAGE_ACCOUNT_KEY:
    secure: AAABABtQu3Y61sRqvJ5PiXn4wKY+auh9/UsakESmwq/TSHSnUx3p6hfiYSzjxK/OeFW/7IWm29UE5M2d5CTP7qocXX0C0Ucydl4gQmvnFW8p9RIt64Ld/7PX4mAPhaSJBDDjtwOkQGjsNog=
  openpipe:AZURE_STORAGE_ACCOUNT_NAME: openpipestorage
  openpipe:AZURE_STORAGE_CONTAINER_NAME: uploadedtrainingdata
  openpipe:DATABASE_URL:
    secure: AAABAO39UTO64OlSnTkBC7sdtQ2F5bZnOhn1yHkL+7IG0115gZ8ufqNOifr79MDkH2WmVQEcLFcVfsIeBVbwr37s8SnKz6Yt0+pDo81N6JxfYjVhqOdPo+XOMloGEUgsZ5Avg4DqqKJnVbkGmVNRGnnBpmbu9nu8
  openpipe:GITHUB_CLIENT_ID:
    secure: AAABAL3M8C6FeKUWaF27HoshIihiTB/YVt2ZT/4JVF2sFPq43RiEcFvQSXJlrQxNf1nVWA==
  openpipe:GITHUB_CLIENT_SECRET:
    secure: AAABADd205NeuFdUsxeK/eMCOEC/FB14/o6iZ2XTCOGFS463ztOvAN2oAm60HYuJOyV1yO1o08jtgpVyPjEHiy3fgQfFxOXP
  openpipe:MODAL_ENVIRONMENT: prod
  openpipe:NEXT_PUBLIC_HOST: https://app.openpipe.ai
  openpipe:NEXT_PUBLIC_POSTHOG_KEY: phc_2tc3AQ798TowPA9FtW2uljz4dKzdiFwpa7EyhPUdKWg
  openpipe:NEXT_PUBLIC_SENTRY_DSN: https://3443df79f39db55f5b60c6d9f41ae684@o4505642008641536.ingest.sentry.io/48
  openpipe:NEXT_PUBLIC_SOCKET_URL: https://querykey-prod-wss.onrender.com
  openpipe:NEXTAUTH_SECRET:
    secure: AAABAKKJBI/ho0yyHuRiI/zImyHNq1ZsQGFmBkBkIHhFUD8UzqW68YaKbLKC+hMU3drGuDHKuR883vTP6MOBRgEFPIMnUFD37V/VMQ==
  openpipe:NEXTAUTH_URL: https://app.openpipe.ai
  openpipe:NODE_ENV: production
  openpipe:OPENAI_API_KEY:
    secure: AAABADqUKEHXX4xWkxl8vWi0/RjkpVTEKy0p96sJiwgEtvVYsfT/qzZui456iTmUJ3USbx/h6hwzOrwoEKzbiV/464HcXiauFJCmipEx3V3S3WM=
  openpipe:OPENPIPE_API_KEY:
    secure: AAABAPSWKH34/0X6RC5yTtNuPRncI3JTDVoWWRNoMGcB6J9hFr2X15IZzYWIIhpffkio87wr89eVv517/rEd6JLrT6yJprqn/zxBMXFB
  openpipe:SENDER_EMAIL: noreply@email.openpipe.ai
  openpipe:SENTRY_AUTH_TOKEN:
    secure: AAABAPbMI/z2KEIz3utl0SaDBjiSUWWyrrHghP4qEfYQgwx7g9Oj55dPoag8zfOEjJ+qrCIW0dAmRNgNKsPgkxEbrC5WKMQBWc3VVxW0nBdxkLHasS/8d3UC+D7bzurjEVOJAvaqSyjvBt70Bs9A+T2XvGtQt/mpCSV7pdoa1dM1stdBvcBkDmnkdfNST916KWfGvg3i2x2HZgSDTo3wsNtqcT7O479yQZHGpIfRSa5NYcXaqKa4+AVhOQvmIPGiUSJFlLolwuUMmq3oK6Zk6tLKEBtDzCYEO1D3KnaNoA==
  openpipe:SMTP_HOST: smtp-relay.brevo.com
  openpipe:SMTP_LOGIN: founders@openpipe.ai
  openpipe:SMTP_PASSWORD:
    secure: AAABAOEiU4VL50BHLBNMrsyuNZPI/YDtxrDQr73KU3fVUPp09Z+Cd0tFPs+KloUu
  openpipe:WORKER_CONCURRENCY: "10"
  openpipe:WORKER_MAX_POOL_SIZE: "30"
  openpipe:deployDomain: openpipestage.com
  openpipe:desiredClusterSize: "1"
  openpipe:eksNodeInstanceType: t3.medium
  openpipe:maxClusterSize: "6"
  openpipe:minClusterSize: "1"
  openpipe:vpcNetworkCidr: 10.0.0.0/16
